apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: usersvc-sds
  name: usersvc-sds
spec:
  type: NodePort
  ports:
  - name: usersvc-sds
    port: 5000
    targetPort: 5000
  selector:
    service: usersvc-sds
